name: jawara
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+34

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.20.2
  file_picker: ^8.1.4
  image_picker: ^1.2.1
  qr_flutter: ^4.1.0
  auto_size_text: ^3.0.0
  crypto: ^3.0.3
  flutter_native_splash: ^2.4.7
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  
  # ML Kit (OCR & Face Detection) - Using google_ml_kit
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_face_detection: ^0.11.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.4
  http: ^1.6.0

  # Export packages
  syncfusion_flutter_xlsio: ^28.1.33
  pdf: ^3.11.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1

  # UI Enhancement for KYC
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.1
  build_runner: ^2.10.4
  go_router: ^17.0.0
  flutter_dotenv: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/illustrations/
    - .env

  fonts:
    - family: Fendysa
      fonts:
        - asset: assets/fonts/Fendysa.ttf

flutter_launcher_icons:
  android: "icons"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"